# Workflow name
name: Deploy Chromatic and GH Pages

# Event for the workflow
on:
  workflow_run:
    workflows: Release
    branches: main
    types:
      - completed

# List of jobs
jobs:
  chromatic:
    # Operating System
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - run: yarn
        #ğŸ‘‡ Adds Chromatic as a step in the workflow
      - uses: chromaui/action@v1
        # Options required for Chromatic's GitHub Action
        with:
          #ğŸ‘‡ Chromatic projectToken,
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GH_TOKEN }}
  build-and-deploy:
    runs-on: ubuntu-latest
    needs: chromatic
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
      - name: Install and Deploy ğŸ”§
        run: | # Install npm packages and build the Storybook files
          yarn
          yarn deploy-storybook -- --ci
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
